Add generate command to add untested routes to baseline file
Tiime-Software/TestedRoutesCheckerBundle pull request #6
Opened 2024-05-06 11:50 UTC by Verena-8

2024-05-06 11:56 UTC, odolbeau requested changes

2024-05-06 11:56 UTC, odolbeau commented on src/Command/CheckCommand.php
> +            }
Pas besoin du `try` / `catch` ici : on veut que ça pète quand le fichier n'a pas pu être généré.

2024-05-06 11:56 UTC, odolbeau commented on src/Command/CheckCommand.php
> +                (new FileRouteStorage($this->routesToIgnoreFile))
Tant qu'à faire, ça vaut le coup d'initialiser ce Storage au début de la méthode pour éviter de le faire deux fois (ligne 47 & ici)

2024-05-06 12:32 UTC, Verena-8 commented on src/Command/CheckCommand.php
> +            }
retiré

2024-05-06 12:33 UTC, Verena-8 commented on src/Command/CheckCommand.php
> +                (new FileRouteStorage($this->routesToIgnoreFile))
j'ai ajouté des setter / getter, est-ce que c'est mieux?

2024-05-07 07:01 UTC, odolbeau commented
Parfait !
Est-ce que tu peux squash tes commits avant de merger stp ?

2024-05-07 07:01 UTC, odolbeau approved these changes

2024-05-07 07:15 UTC, merged